spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_batch_fetch_size: 1000
      hibernate.default_schema: public
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database: POSTGRESQL
    database-platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/test_db?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      password: password
      port: 6379
      jedis:
        pool:
          enabled: true
      connect-timeout: 300
      timeout: 300